CaseStudy_PrimeEdu/Controllers/CoursesController.cs
using CaseStudy_PrimeEdu.Data;
using CaseStudy_PrimeEdu.Data.Services;
using CaseStudy_PrimeEdu.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Query;

namespace CaseStudy_PrimeEdu.Controllers
{
    public class CoursesController : Controller
    {
        private readonly ICoursesService _service;

        public CoursesController(ICoursesService service)
        {
            _service = service;
        }

        //CREATE
        public async Task<IActionResult> Create()
        { 
            Course course = new Course();
            course.TeacherNames = await _service.GetAvailableTeachersList();
            return View(course);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name, Description, Location, CourseDuration, TeacherId")] Course course)
        {
            if (!ModelState.IsValid)
            {
                course.TeacherNames = await _service.GetAvailableTeachersList();                
                return View(course);
            }

            await _service.AddAsync(course);

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> AddStudentToCourse(int id, int courseId)
        {
            await _service.AddStudentToCourse(id, courseId);
            return RedirectToAction(nameof(Students), new { id = courseId });
        }

        //READ 
        public async Task<IActionResult> Details(int id)
        {
            var data = await _service.GetByIdAsync(id);
            if (data == null) return View("NotFound");
            return View(data);
        }
        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync();

            //Teacher column service
            foreach (var item in data)
            {
                if (item.TeacherId > 0)
                {
                    item.TeacherName = await _service.GetCourseTeacherById(item.TeacherId);
                }
            }
            return View(data);
        }
        public async Task<IActionResult> Students(int id) //Index->Students(Grid Form)->AddStudent
        {
            var data = await _service.GetCourseStudents(id);
            ViewData["CourseId"] = id;
            return View(data);
        }
        public async Task<IActionResult> AddStudent(int id) //to course
        {
            var data = await _service.GetAllStudentsAsync(id);
            if (data == null) return View("NotFound");

            ViewData["CourseId"] = id;
            return View(data);
        }
        public async Task<IActionResult> Tests(int id) //Index->Tests(Grid Form)->AddStudent
        {
            var data = await _service.GetCourseTests(id);
            ViewData["CourseId"] = id;
            return View(data);
        }
        public async Task<IActionResult> TestResults(int id, int courseId)
        {
            var data = await _service.GetTestResultsAsync(id);
            if (data == null) return View("NotFound");

            ViewData["CourseId"] = courseId;
            return View(data);
        }

        //UPDATE
        public async Task<IActionResult> Edit(int id)
        {

            var data = await _service.GetByIdAsync(id);
            if (data == null) return View("NotFound");

            data.TeacherNames = await _service.GetAvailableTeachersList();
            ViewData["CourseId"] = id;
            return View(data);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id, Name, Description, Location, CourseDuration, TeacherId")] Course course)
        {
            if (!ModelState.IsValid)
            {
                return View(course);
            }

            await _service.UpdateAsync(id, course);

            return RedirectToAction(nameof(Index));
        }

        //DELETE
        public async Task<IActionResult> Delete(int id)
        {
            var data = await _service.GetByIdAsync(id);
            if (data == null) return View("NotFound");

            await _service.DeleteAsync(id);

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> DeleteStudent(int id, int courseId)
        {
            await _service.DeleteCourseStudentAsync(id, courseId);

            return RedirectToAction(nameof(Students), new {id = courseId});
        }

        //TODO    
        public IActionResult Error()
        {
            return View();
        }
    }
}

CaseStudy_PrimeEdu/Controllers/StudentsController.cs
using CaseStudy_PrimeEdu.Data;
using CaseStudy_PrimeEdu.Data.Services;
using CaseStudy_PrimeEdu.Models;
using Microsoft.AspNetCore.Mvc;

namespace CaseStudy_PrimeEdu.Controllers
{
    public class StudentsController : Controller
    {
        private readonly IStudentsService _service;

        public StudentsController (IStudentsService service)
        {
            _service = service;
        }

        //CREATE
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FirstName, LastName, Description")]Student student)
        {
            if(!ModelState.IsValid)
            {
                return View(student);
            }

            await _service.AddAsync(student);

            return RedirectToAction(nameof(Index));
        }

        //READ 
        public async Task<IActionResult> Details(int id)
        {
            var data = await _service.GetByIdAsync(id);
            if (data == null) return View("NotFound");
            return View(data);
        }
        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync();
            return View(data);
        }

        //EDIT
        public async Task<IActionResult> Edit(int id)
        {
            var data = await _service.GetByIdAsync(id);
            if (data == null) return View("NotFound");
            return View(data);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id, FirstName, LastName, Description")] Student student)
        {
            if (!ModelState.IsValid)
            {
                return View(student);
            }

            await _service.UpdateAsync(id, student);

            return RedirectToAction(nameof(Index));
        }

        //DELETE
        public async Task<IActionResult> Delete(int id)
        {
            var data = await _service.GetByIdAsync(id);
            if (data == null) return View("NotFound");
            return View(data);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var data = await _service.GetByIdAsync(id);
            if (data == null) return View("NotFound");

            await _service.DeleteAsync(id);

            return RedirectToAction(nameof(Index));
        }

        //TODO    
        public IActionResult Error()
        {
            return View();
        }       

    }
}

CaseStudy_PrimeEdu/Controllers/TeachersController.cs
using CaseStudy_PrimeEdu.Data;
using CaseStudy_PrimeEdu.Data.Services;
using CaseStudy_PrimeEdu.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CaseStudy_PrimeEdu.Controllers
{
    public class TeachersController : Controller
    {
        private readonly ITeachersService _service;

        public TeachersController(ITeachersService service)
        {
            _service = service;
        }

        //CREATE
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FirstName, LastName, Title, Description")] Teacher teacher)
        {
            if (!ModelState.IsValid)
            {
                return View(teacher);
            }

            await _service.AddAsync(teacher);

            return RedirectToAction(nameof(Index));
        }

        //READ 
        public async Task<IActionResult> Details(int id)
        {
            var data = await _service.GetByIdAsync(id);
            if (data == null) return View("NotFound");
            return View(data);
        }
        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync();
            return View(data);
        }

        //EDIT
        public async Task<IActionResult> Edit(int id)
        {
            var data = await _service.GetByIdAsync(id);
            if (data == null) return View("NotFound");
            return View(data);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id, FirstName, LastName, Title, Description")] Teacher teacher)
        {
            if (!ModelState.IsValid)
            {
                return View(teacher);
            }
                        
            await _service.UpdateAsync(id, teacher);

            return RedirectToAction(nameof(Index));
        }

        //DELETE
        public async Task<IActionResult> Delete(int id)
        {
            var data = await _service.GetByIdAsync(id);
            if (data == null) return View("NotFound");
            return View(data);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var data = await _service.GetByIdAsync(id);
            if (data == null) return View("NotFound");

            await _service.DeleteAsync(id);

            return RedirectToAction(nameof(Index));
        }

        //TODO    
        public IActionResult Error()
        {
            return View();
        }
    }
}

CaseStudy_PrimeEdu/Controllers/TestsController.cs
using CaseStudy_PrimeEdu.Data;
using CaseStudy_PrimeEdu.Data.Services;
using CaseStudy_PrimeEdu.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CaseStudy_PrimeEdu.Controllers
{
    public class TestsController : Controller
    {
        private readonly ITestsService _service;

        public TestsController(ITestsService service)
        {
            _service = service;
        }

        //CREATE
        public async Task<IActionResult> Create()
        {
            Test test = new Test();
            test.CourseList = await _service.GetAvailableCoursesList();
            return View(test);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name, Description, CourseId")] Test test)
        {
            if (!ModelState.IsValid)
            {
                test.CourseList = await _service.GetAvailableCoursesList();
                return View(test);
            }

            await _service.AddAsync(test);

            return RedirectToAction(nameof(Index));
        }

        //READ 
        public async Task<IActionResult> Details(int id)
        {
            var data = await _service.GetByIdAsync(id);
            if (data == null) return View("NotFound");
            return View(data);
        }

        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync();
            return View(data);
        }

        //EDIT
        public async Task<IActionResult> Edit(int id)
        {
            var data = await _service.GetByIdAsync(id);
            if (data == null) return View("NotFound");
            return View(data);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id, Name, Description, CourseId")] Test test)
        {
            if (!ModelState.IsValid)
            {
                return View(test);
            }

            await _service.UpdateAsync(id, test);

            return RedirectToAction(nameof(Index));
        }

        //DELETE
        public async Task<IActionResult> Delete(int id)
        {
            var data = await _service.GetByIdAsync(id);
            if (data == null) return View("NotFound");
            return View(data);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var data = await _service.GetByIdAsync(id);
            if (data == null) return View("NotFound");

            await _service.DeleteAsync(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

CaseStudy_PrimeEdu/Views/Shared/NotFound.cshtml
<div class="row text-center">
    <div class="col-md-6 offset-3">
        <h1 class="text-xxl-center">We can't retrieve what you are looking for</h1>
        <hr />
        <a class="btn btn-outline-success" asp-controller="Classes" asp-action="Index">Home Page</a>
    </div>    
</div>

CaseStudy_PrimeEdu/Views/Shared/_Identity.cshtml
@*
@using Microsoft.AspNetCore.Identity;

@inject UserManager<ApplicationUser> UserManager;
*@

@if (!User.Identity.IsAuthenticated)
{
    @*LOGIN BUTTON*@
    <a class="btn btn-outline-success my-2 my-sm-0" asp-controller="Account" asp-action="Login">
        <i class="bi bi-box-arrow-in-right"></i> Login
    </a>
    <span style="padding: 5px;"></span>

    @*REGISTER BUTTON*@
    <a class="btn btn-outline-primary my-2 my-sm-0" asp-controller="Account" asp-action="Register">
        <i class="bi bi-person-plus"></i> Register
    </a>
} 
else
{
    <span style="padding: 5px;"></span>

    @*LOGOUT BUTTON*@
    <form asp-controller="Account" asp-action="Logout">
        <button class="btn btn-outline-danger my-2 my-sm-0">
            <i class="bi bi-box-arrow-in-right"></i> Log out
        </button>
    </form>
}

CaseStudy_PrimeEdu/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CaseStudy_PrimeEdu</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CaseStudy_PrimeEdu.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                @*HOME LOGO/BUTTON*@
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CaseStudy_PrimeEdu</a>
                @*CONTENT DROPDOWN*@
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="bi bi-mortarboard-fill"></i> Content
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-controller="Courses" asp-action="Index"> <i class="bi bi-house"></i> Courses</a>
                                <a class="dropdown-item" asp-controller="Teachers" asp-action="Index"> <i class="bi bi-person-check-fill"></i> Teachers</a>
                                <a class="dropdown-item" asp-controller="Students" asp-action="Index"> <i class="bi bi-geo-fill"></i> Students</a>
                                <a class="dropdown-item" asp-controller="Tests" asp-action="Index"> <i class="bi bi-pencil"></i> Tests</a>
                            </div>
                        </li>
                    </ul>
                </div>

                @*await Html.RenderPartialAsync("_Identity")*@

                <partial name="_Identity.cshtml" />
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PrimeEdu - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>